## Importation des librairies

In [254]:
import pandapower as pp
import pandas as pd
import numpy as np

import pp_heig_simulation as pp_sim
import pp_heig_plot as pp_plot
from datetime import time

## Récuperation du fichier pickle

In [255]:
net_pickle = pp.from_pickle('input-data/trey_net_student.p')

net_pickle.bus # Affiche les informations des bus, un slack et 11 PQ (charges)

            name   type   zone  in_service
0     STMT003438     PQ  Trafo        True
1     CDBT004764     PQ  North        True
2     CDBT003746     PQ  North        True
3     CDBT004760     PQ  North        True
4     CDBT012139     PQ  North        True
5     CDBT900784     PQ  North        True
6     CDBT901452     PQ  South        True
7     CDBT004774     PQ  South        True
8     CDBT901604     PQ  South        True
9     CDBT016055     PQ  South        True
10            N1     PQ  South        True
11         60437     PQ  South        True
12  STMT003438HV  Slack  Trafo        True

In [256]:
net_pickle.line

              name  from_bus  to_bus  g_us_per_km   df std_type  in_service
0     GKN3x150_150         0       1          0.0  1.0     None        True
1   GKN3x150_150_2         1       2          0.0  1.0     None        True
2       GKN3X95_95         1       3          0.0  1.0     None        True
3       GKT3X50_50         3       4          0.0  1.0     None        True
4     GKT3X50_50_2         4       5          0.0  1.0     None        True
5   GKN3x150_150_3         0       6          0.0  1.0     None        True
6     GKN3X95_95_2         6       7          0.0  1.0     None        True
7   GKN3x150_150_4         7       8          0.0  1.0     None        True
8       GKN3X50_50         7       9          0.0  1.0     None        True
9     GKN3X50_50_2         6      10          0.0  1.0     None        True
10    GKN3X240_240         0      11          0.0  1.0     None        True

In [257]:
# Configure les paramètres des lignes du réseau
net_pickle.line.insert(2,"length_km", [0.18, 0.1, 0.115, 0.08, 0.09, 0.135, 0.1, 0.205, 0.085, 0.255, 0.340])
net_pickle.line.insert(2, "r_ohm_per_km", [0.124, 0.124, 0.193, 0.387, 0.387, 0.124, 0.193, 0.124, 0.387, 0.387, 0.0754])
net_pickle.line.insert(2, "x_ohm_per_km", [0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07])
net_pickle.line.insert(2, "c_nf_per_km", [349, 349, 338, 298, 298, 349, 338, 349, 298, 298, 346])
net_pickle.line.insert(2, "max_i_ka", [0.4, 0.4, 0.252, 0.170, 0.170, 0.4, 0.252, 0.4, 0.170, 0.170, 0.512])
net_pickle.line.insert(2, "parallel", [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [258]:
net_pickle.line

,name,from_bus,parallel,max_i_ka,c_nf_per_km,x_ohm_per_km,r_ohm_per_km,length_km,to_bus,g_us_per_km,df,std_type,in_service
0,GKN3x150_150,0,1,0.400,349,0.07,0.1240,0.180,1,0.0,1.0,None,True
1,GKN3x150_150_2,1,1,0.400,349,0.07,0.1240,0.100,2,0.0,1.0,None,True
2,GKN3X95_95,1,1,0.252,338,0.07,0.1930,0.115,3,0.0,1.0,None,True
3,GKT3X50_50,3,1,0.170,298,0.07,0.3870,0.080,4,0.0,1.0,None,True
4,GKT3X50_50_2,4,1,0.170,298,0.07,0.3870,0.090,5,0.0,1.0,None,True
5,GKN3x150_150_3,0,1,0.400,349,0.07,0.1240,0.135,6,0.0,1.0,None,True
6,GKN3X95_95_2,6,1,0.252,338,0.07,0.1930,0.100,7,0.0,1.0,None,True
7,GKN3x150_150_4,7,1,0.400,349,0.07,0.1240,0.205,8,0.0,1.0,None,True
8,GKN3X50_50,7,1,0.170,298,0.07,0.3870,0.085,9,0.0,1.0,None,True
9,GKN3X50_50_2,6,1,0.170,298,0.07,0.3870,0.255,10,0.0,1.0,None,True
10,GKN3X240_240,0,1,0.512,346,0.07,0.0754,0.340,11,0.0,1.0,None,True

In [259]:
net_pickle.trafo # Affiche les informations des transformateurs, ici un seul transformateur

,name,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,i0_percent,vector_group,vk0_percent,vkr0_percent,mag0_percent,mag0_rx,si0_hv_partial,shift_degree,tap_side,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,tap_phase_shifter,parallel,std_type,df,in_service
0,STMT003438,12,0,0.63,18.3,0.42,4.0,0.42,0.65,1.8,Dyn,3.0,0.75,0.3,1.9,1.9,0.0,lv,0,-3,3,2.0,0.0,-3,False,1,None,1.0,True

In [260]:
net_pickle.bus.insert(3, "vn_kv", [0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 0.42, 18.3]) # Ajoute la tension nominale aux bus
net_pickle.bus

            name   type   zone  vn_kv  in_service
0     STMT003438     PQ  Trafo   0.42        True
1     CDBT004764     PQ  North   0.42        True
2     CDBT003746     PQ  North   0.42        True
3     CDBT004760     PQ  North   0.42        True
4     CDBT012139     PQ  North   0.42        True
5     CDBT900784     PQ  North   0.42        True
6     CDBT901452     PQ  South   0.42        True
7     CDBT004774     PQ  South   0.42        True
8     CDBT901604     PQ  South   0.42        True
9     CDBT016055     PQ  South   0.42        True
10            N1     PQ  South   0.42        True
11         60437     PQ  South   0.42        True
12  STMT003438HV  Slack  Trafo  18.30        True

In [261]:
# Dans un foyer typique, la consommation électrique moyen est d'envrion 5000 kwH par an, ce qui équivaut 
# à une puissance active moyenne de 570 W par foyer. un foyer possédant principalement des charges résistives, le cosφ est proche de 1 
# et donc la puissance réactive est négligeable.
P_load_mean = 0.00057  # Puissance active moyenne par charge en MW

Q_load_mean = 0.0   # Puissance réactive moyenne par charge en MV
P_CDBT004764 = P_load_mean * 8
P_STMT003438 = P_CDBT901452 = P_load_mean * 5
P_CDBT900784 = P_CDBT012139 = P_CDBT004760 = P_CDBT004774 = P_CDBT016055 = P_load_mean * 4
P_CDBT003746 = P_load_mean * 3
N1 = P_60437 = P_CDBT901604 = P_load_mean
net_pickle.load.insert(2, "p_mw", [P_STMT003438, P_CDBT004764, P_CDBT003746, P_CDBT004760, P_CDBT012139, P_CDBT900784, P_CDBT901452, P_CDBT004774, P_CDBT901604, P_CDBT016055, N1, P_60437])
net_pickle.load.insert(2, "q_mvar", [Q_load_mean] * 12)
net_pickle.load.insert(6, "scaling", [1] * 12)  # Facteur d'échelle pour chaque charge (1 = pas de changement)
net_pickle.load

,name,bus,q_mvar,p_mw,const_z_percent,const_i_percent,scaling,sn_mva,in_service,type
0,STMT003438,0,0.0,0.00285,0.0,0.0,1,None,True,wye
1,CDBT004764,1,0.0,0.00456,0.0,0.0,1,None,True,wye
2,CDBT003746,2,0.0,0.00171,0.0,0.0,1,None,True,wye
3,CDBT004760,3,0.0,0.00228,0.0,0.0,1,None,True,wye
4,CDBT012139,4,0.0,0.00228,0.0,0.0,1,None,True,wye
5,CDBT900784,5,0.0,0.00228,0.0,0.0,1,None,True,wye
6,CDBT901452,6,0.0,0.00285,0.0,0.0,1,None,True,wye
7,CDBT004774,7,0.0,0.00228,0.0,0.0,1,None,True,wye
8,CDBT901604,8,0.0,0.00057,0.0,0.0,1,None,True,wye
9,CDBT016055,9,0.0,0.00228,0.0,0.0,1,None,True,wye
10,N1,10,0.0,0.00057,0.0,0.0,1,None,True,wye
11,60437,11,0.0,0.00057,0.0,0.0,1,None,True,wye

In [262]:
net_pickle.ext_grid.insert(2, "bus", 12)  # Connecte la source externe au bus 12 (HT)

In [263]:
pp_plot.plot_power_network(
    net=net_pickle,
    plot_title="Configuration du réseau électrique",
    filename="custom_power_network.png",
)

In [264]:
pp.runpp(net_pickle)
pd.DataFrame(net_pickle._ppc["internal"]["Ybus"].toarray()).round(1)
pp_plot.plot_powerflow_result(
    net=net_pickle,
    plot_title="Exercice Power flow 1 : Problème 1 - results",
    filename="net_ex_pf_1_pb_1_grid_pp_result",
)

In [265]:
Kwh_m2_one_housing = 
Kwh_m2_multi_house =
Kwh_m2_farm =
Kwh_m2_industrial =
Kwh_m2_church =

P_load_mean_one_housing = 0.00057  # Puissance active moyenne par charge en MW
P_load_mean_farm =
P_load_mean_industrial =
P_load_mean_church =
Q_load_mean = 0.0   # Puissance réactive moyenne par charge en MV
P_CDBT004764 = P_load_mean * 8
P_STMT003438 = P_CDBT901452 = P_load_mean * 5
P_CDBT900784 = P_CDBT012139 = P_CDBT004760 = P_CDBT004774 = P_CDBT016055 = P_load_mean * 4
P_CDBT003746 = P_load_mean * 3
N1 = P_60437 = P_CDBT901604 = P_load_mean
net_pickle.load.insert(2, "p_mw", [P_STMT003438, P_CDBT004764, P_CDBT003746, P_CDBT004760, P_CDBT012139, P_CDBT900784, P_CDBT901452, P_CDBT004774, P_CDBT901604, P_CDBT016055, N1, P_60437])
net_pickle.load.insert(2, "q_mvar", [Q_load_mean] * 12)
net_pickle.load.insert(6, "scaling", [1] * 12)  # Facteur d'échelle pour chaque charge (1 = pas de changement)
net_pickle.load

SyntaxError: invalid syntax (2456517512.py, line 1)